# Generated by Django 4.2.1 on 2023-06-07 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_uvi_area_no_uvi_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uvi',
            old_name='area_no',
            new_name='areaNo',
        ),
    ]
