# Generated by Django 4.2.1 on 2023-06-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_uvi_time_uvi_uvi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uvi',
            name='UVI',
        ),
        migrations.AddField(
            model_name='uvi',
            name='UVI_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uvi',
            name='areaNo',
            field=models.CharField(max_length=255),
        ),
    ]
